dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

env:
  - TEST_TYPE=UT
  - CITA_DOCKER_IMAGE_TAG_NAME=sha3_d8f6587  TEST_TYPE=ST TEST_CITA_VERSION=CITA20.2.0
  - CITA_DOCKER_IMAGE_TAG_NAME=sha3_48cf859  TEST_TYPE=ST TEST_CITA_VERSION=CITA1.0.1
  - CITA_DOCKER_IMAGE_TAG_NAME=sha3_88b90bb  TEST_TYPE=ST TEST_CITA_VERSION=CITA0.25
  - CITA_DOCKER_IMAGE_TAG_NAME=sha3_1f10bc8  TEST_TYPE=ST TEST_CITA_VERSION=CITA0.24
  - CITA_DOCKER_IMAGE_TAG_NAME=sha3_b1e3048  TEST_TYPE=ST TEST_CITA_VERSION=CITA0.23.1

sudo: required  # as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

# Avoid uploading cache after every build with Gradle - see https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  # upgrade gradle to 5.0
  - test -e $HOME/.gradle/caches/gradle-5.0.zip || sudo wget -q https://services.gradle.org/distributions/gradle-5.0-all.zip -O $HOME/.gradle/caches/gradle-5.0.zip > debug.log
  - sudo unzip $HOME/.gradle/caches/gradle-5.0.zip  > debug.log
  - ./gradle-5.0/bin/gradle -v

script: bash ./scripts/run.sh

